### ISSUE TITLE
Syntax Error running script

### ISSUE THREAD

**Issue by SyRaza** [radj/AndroidSMSBackupRestoreCleaner#5]
Hey Radj,

First off, thanks for coming up with this solution.
Second, I don't know anything about Python but I'm trying to learn so I can use the cleaner. I've placed both the sms.xml and the clean.py file in the same folder.

![a4332762a649d50ad16c2d2a4a801ec1](https://cloud.githubusercontent.com/assets/13445113/8817329/2556ac84-3000-11e5-826e-b608e18e5692.png)

When I try to run the script, I get a syntax error for some reason. 
![60b6883a8b04a401cc1577e733ec73f6](https://cloud.githubusercontent.com/assets/13445113/8817349/50fad39c-3000-11e5-8ce1-a59c6bfa47b7.png)

Any help would be appreciated.
Thank you!

**Comment by radj** [comment]
Hi @SyRaza, it looks like you have Python 3. The script only supports Python 2 right now.
